% calculateIRFTransform(NormalizedIRF, TimeAxis, Omega)
% Make sure that sum(NormalizedIRF) == 1
function IRFTransform = calculateIRFTransform(NormalizedIRF, TimeAxis, ...
    Omega)
    IRFTransform = reshape(NormalizedIRF, 1, []) * ...
        cos(Omega * reshape(TimeAxis, [], 1)) + ...
        1i * reshape(NormalizedIRF, 1, []) * ...
        sin(Omega * reshape(TimeAxis, [], 1));
end
